### ISSUE TITLE
clicking outside the widget sets display:none to input field

### ISSUE THREAD

**Issue by jamiroconca** [jdewit/bootstrap-timepicker#100]
it seems that timepicker show and hide works on the timepicker container <div class="input-append bootstrap-timepicker"> instead of widget only
![2013-03-13 10-15-49](https://f.cloud.github.com/assets/357607/252999/faef5474-8bbe-11e2-8798-13507dfa82a2.png)
- latest bootstrap-timepicker
- bootstrap.js v2.2.2
- jquery v1.8.3

commenting out 
/*
this.$element.trigger({
        'type': 'hide.timepicker',
        'time': {
            'value': this.getTime(),
            'hours': this.hour,
            'minutes': this.minute,
            'seconds': this.second,
            'meridian': this.meridian
         }
      });
*/

seems to fix, but doesn't sound like a correct solution to me

**Comment by jdewit** [comment]
This is by design. I'm open to alternative solutions.
