### ISSUE TITLE
timepicker not picking up default time

### ISSUE THREAD

**Issue by kneidels** [jdewit/bootstrap-timepicker#102]
hi folks

using bootstrap 2.0.3 

i have an issue that when loading database drawn values for a time - timepicker doesnt pick them up.

sample of scenario:  http://bit.ly/YjublF 

any help appreciated!
Thanks!

**Comment by danawoodman** [comment]
:+1:

**Comment by MikeWills** [comment]
:+1:

**Comment by mrkre** [comment]
:+1:

**Comment by mrhota** [comment]
An example here would be nice, but new release doesn't support bootstrap 2. Please reopen if this is still an issue with newer releases.

**Comment by kneidels** [comment]
Thanks so much for the reply, 2 years down the line
an example was supplied in the original post.

**Comment by mrhota** [comment]
1. Your link is broken. And---unhelpfully---obfuscated.
2. You don't have to be a jerk; I recently took over maintainership of this project. You're welcome.
