### ISSUE TITLE
Bootstrap modal footer hides dropdown menu

### ISSUE THREAD

**Issue by michalmoravek** [jdewit/bootstrap-timepicker#104]
I'm using bootstrap 2.3.0 and the newest timepicker, but I have problem with showing timepicker dropdown in modal window - it is showed under modal footer.
![timepicker](https://f.cloud.github.com/assets/3875243/286225/3266238c-9237-11e2-80be-a4f1ee94100f.jpg)

**Comment by michaelahlers** [comment]
Running into this problem, too. Using 0.2.3.

**Comment by 5im0n** [comment]
Got the same problem.
I think the Timepicker should be create out of the modal.

**Comment by michaelahlers** [comment]
Append the element to the body?

**Comment by 5im0n** [comment]
Yes, because the problem isn't due to a z-index.
For instance the plugin Bootstrap datepicker create calendar in the body.
http://www.eyecon.ro/bootstrap-datepicker/

**Comment by jtmille3** [comment]
+1

**Comment by paultregoing** [comment]
You can probably work around it by adding "overflow-y: visible" to .modal-body

**Comment by 5im0n** [comment]
The problem is solved with Bootstrap 3 Modal

**Comment by jdewit** [comment]
I'm in the process of updating to bs3.0. Closing this since it will no longer be an issue with 3.0.
