### ISSUE TITLE
Applying bootstrap.css only to Timepicker elements

### ISSUE THREAD

**Issue by alexpyoung** [jdewit/bootstrap-timepicker#105]
I don't want to include bootstrap.css in my page because it will apply conflicting and unwanted styles to many different elements. I am trying to apply the Bootstrap style only to the Timepicker. I used a regex to statically prepend a descendent selector (that corresponds to my wrapper) to all CSS selectors in bootstrap.css. However, the Timepicker still doesn't appear correctly. Any idea why?

**Comment by jdewit** [comment]
Sorry for the late reply. Without any code I have no clue what could be wrong. Reopen if you still have issues.
