### ISSUE TITLE
Template dropdown its not working

### ISSUE THREAD

**Issue by silviomoreto** [jdewit/bootstrap-timepicker#106]
I already use bootstrap-timepicker (6 motnhs ago) and now I updated to the newest version (css and js). But the dropdown stoped to open, the timepicker is working but just in the "no template" mode.

The boostrap version that Im using is: 2.2.1

and Im calling bootstrap-timepicker like this:

```
    $('#id_start_time').timepicker({
        template: 'dropdown',
        defaultTime: 'value',
        showMeridian: false,
        minuteStep: 5
    });
```

Anyone knwos how to fix it? Do I need to add something extra if installing with the manual way?

Ty

**Comment by sq2** [comment]
In your HTML, try changing the class name:

``` html
<span class="input-append bootstrap-timepicker">
```

It seems that bootstrap-timepicker-component was dropped in this version.

**Comment by silviomoreto** [comment]
Yes, now is working, but on someplaces without the teamplate on the input to select hours and minutes
