### ISSUE TITLE
defaultTime: 'current' with minuteStep step to future, not past.

### ISSUE THREAD

**Issue by oller** [jdewit/bootstrap-timepicker#110]
```
$('.timepicker-start').timepicker({
    defaultTime: 'current',
    minuteStep: 15,
});
```
### Is there anyway to do arithmetic on 'current'?

When used in conjunction with minuteStep, it seems to always go _back_ to the nearest interval.  I'd like it to go forward to the nearest step interval in the future, and was wondering if there's anyway to do this without having to resort to server-side date arithmetic?

**Comment by jdewit** [comment]
I agree, current time should be the closest interval into the future. Will fix this soon.
