### ISSUE TITLE
timepicker-to-timepicker UI cleanup

### ISSUE THREAD

**Issue by yankeeinlondon** [jdewit/bootstrap-timepicker#12]
I'm attempting to use the timepicker in "dropdown" style but when I tab or click out of a timepicker field and onto ANOTHER timepicker control the original control is left visible on the screen. Here are the steps I've taken (just to ensure you have context and I haven't done anything silly):
1. I have made sure the .less file has compiled to .css successfully and the .css file is referenced by the HTML
2. I have the following HTML in my form:
   `<input class="span2 dropdown-timepicker" id="start-time" type="text" name="start-time" data-provide="timepicker">`
3. I have included the JS call to timepicker. I load content via a series of AJAX templates and each "template" that is connected to timepicker with this call:
   `$( targetString ).find('.timepicker').timepicker();`
4. When presented with the form initially it looks fine; when clicking on a timepicker field it too behaves correctly but ...
5. When leaving the field the UI control remains on the screen if -- and only if -- the next control is ALSO a timepicker
6. When I eventually do click on a form element that is NOT a timepicker than all timepicker controls are removed.

I have created a screenshot here: http://www.flickr.com/photos/14261777@N00/7201834692/

**Comment by yankeeinlondon** [comment]
Actually as a slight amendment to my initial statement:
1. This is being done a top of a bootstrap modal box (not sure that that should have any bearing but worth mentioning)
2. I have now done further testing and "clicking" onto a non-timepicker form element does indeed remove the UI elements of the timepicker but tabbing out of a timepicker to a non-timepicker element does NOT remove the UI elements

**Comment by lpgauth** [comment]
I have the same issue. +1

**Comment by Theadd** [comment]
Same here, and not just tabbing out of a timepicker does NOT remove the UI elements, tabbing in does not show them.

**Comment by oller** [comment]
+1 for this, am going to have a little tinker, shall update with any progress.....

**Comment by jdewit** [comment]
The issue lies with the hide event not being triggered because of the e.stopPropagation in the show method. I just fixed the issue by calling a click() event on the html element manually. If anyone has a better solution have at her.
