### ISSUE TITLE
Demo for documentation.

### ISSUE THREAD

**Issue by tomasAlabes** [jdewit/bootstrap-timepicker#120]
Hi @jdewit, I wanted to mail you but I couldn't find your email. 
I made this [simple web site](http://tomasalabes.github.io/sleepCycles/) a while ago and it seems a good example of use of your library. The code is [here](https://github.com/tomasAlabes/sleepCycles) for users to see. 
If you like it you could add it as a demo in your site, that's all.
Nice work!

**Comment by jdewit** [comment]
Hey Tomas,

Nice to see it working well for you!
