### ISSUE TITLE
error in the example code

### ISSUE THREAD

**Issue by DilipShah** [jdewit/bootstrap-timepicker#126]
Great component!

On page http://jdewit.github.io/bootstrap-timepicker/index.html
in the event handler examples at the bottom of the page, it looks like it should be 
e.time.hours, e.time.minutes, e.time.seconds
instead of 
e.time.hour, e.time.minute, e.time.second

**Comment by spooknick** [comment]
I second that, just found it out too

**Comment by mrhota** [comment]
Fixed already
