### ISSUE TITLE
timpicker has issues with bootstrap modal

### ISSUE THREAD

**Issue by pdeva** [jdewit/bootstrap-timepicker#143]
Here is the plunkr
http://plnkr.co/edit/vQehXEon3JuO0EEpoL4o?p=preview
1. Note that the timepicker outside the modal on the page itself works fine.
2. open the modal, and try clicking the time icon.
3. notice how the popup stays 'inside' the dialog.
   https://www.evernote.com/shard/s9/sh/3757799c-79e6-43af-8085-aa946d1b72c6/51166240b9a5a0ad5c1e360fbafd93a0
4. this does not happen for the datepicker view.
   https://www.evernote.com/shard/s9/sh/04694436-ed4f-4500-85cd-c35672f91879/890f9f27cefe2895fd9133d000cef15e

**Comment by j-hernandez** [comment]
I ran into this recently. My solution isn't really ideal but it got the job done for my particular case. I just added a class to the `modal-body` div with the following css:

``` css
    overflow-y:visible !important;
```

Again, not ideal, but worked for me. The modal I'm working with has a table that contains rows of inputs, two of which are datepickers. Rows can be added or removed on the fly and I haven't had any issues. Hope this helps!

**Comment by pdeva** [comment]
It seems the issue is that the generated 'table' of the timepicker is contained within the `input-append` div, while with the datepicker it is generated outside the modal body completely.

Timepicker:
http://screencast.com/t/WIZNbmxb7zXV

Datepicker:
http://screencast.com/t/LRFQblrvxM6L

**Comment by j-hernandez** [comment]
I'll take another look at my implementation when I have a moment and see if I can spot anything. Looking back on this I feel like I may have done something else to get this to work 100%

**Comment by fdaugan** [comment]
This issue can be closed  since the last version works fine with popup and Bootstrap 2.3.2

**Comment by mrhota** [comment]
The plunkr doesn't work. The last comment indicates that this isn't an issue any more. We can open a new ticket if necessary.
