### ISSUE TITLE
Tab after manual time enter

### ISSUE THREAD

**Issue by bdk0172** [jdewit/bootstrap-timepicker#152]
If I use a default timepicker and type in "9:45 a" and press the tab key, it recognizes it as a valid time by updating the value to "09:45 AM", but sets the cursor focus to the minutes entry.  Is there a way to have it set focus to the next valid input element after the timepicker when it recognizes that a valid time has been entered instead of having to tab twice, once through minutes and once through AM/PM, to get to the next input?

**Comment by jdewit** [comment]
Currently working on improving the setTime method to allow for this.
