### ISSUE TITLE
Project still live?

### ISSUE THREAD

**Issue by jesselathamdev** [jdewit/bootstrap-timepicker#153]
Hey there,

Haven't seen any activity lately, especially with the release of Bootstrap 3 now out for a number of weeks.

Plans to keep up this excellent project or do we need to start searching for another?

Cheers, and thanks for the hard work you've put into this so far.  Hoping for more.
Jess

**Comment by jdewit** [comment]
Yes. Been too busy I guess. I will try to find some time in the next few weeks to get it up to snuff.

**Comment by cmrockwell** [comment]
Hi.  I'd like to offer my help on this project.  Can you recommend were to start?  Even if just contributing to the documentation.  For example from the docs it was not clear how to control the timepicker via JavaScript.  Looking at the source I saw it is done by passing 'incrementMinute' as a parameter to the timepicker function.  Thanks again....

**Comment by jesselathamdev** [comment]
Awesome - thanks for the response Joris.  Looking forward to the updates.

Jess
