### ISSUE TITLE
Closing picker when instantiated on an element on a modal dialogue closes the dialogue as well

### ISSUE THREAD

**Issue by MindWire** [jdewit/bootstrap-timepicker#16]
The hidden trigger in the hide method will also close a modal dialogue if the element the picker is attached to in on it. The offending line is:

``` javascript
this.$element.trigger('hidden');
```

I imagine its due to event propagation and adding a default handler if one is not added to the element instantiating the picker with the function being to simply stop propagation would solve the problem. I will test further scenarios.

**Comment by thelonecabbage** [comment]
bump.

I am also having this issue.  Kills the interface (locked under modal background) when the picker closes.

**Comment by nealvora** [comment]
thelonecabbage's fix works for my related issue. i had the timepicker in a modal. i also had some javascript associated with the "hidden" event on that modal (the modal ID was the selector of that javascript). that javascript would incorrectly get run anytime the dropdown-menu was hidden.

**Comment by yekibud** [comment]
@thelonecabbage You should submit a pull request for this.

@jdewit You're lagging on your pull requests.

**Comment by jdewit** [comment]
ya ya, i'll be able to approve pull requests with more confidence now that there are unit tests.

This issue should be resolved. Timepicker now uses namespaced events.
