### ISSUE TITLE
bower link is dead and it's unclear how to include in web app

### ISSUE THREAD

**Issue by deanhiller** [jdewit/bootstrap-timepicker#166]
on this page, link to bower leads to 404 http://jdewit.github.io/bootstrap-timepicker/index.html

and googling and looking at bower it is very unclear how to install timepicker since the install moves stuff to some bower directory.  We need *.js scripts in our webapp/public directory not some other directory on the OS.  More explicit instructions would be nice and I still unsure whether bower works on a MAC OS or not as well.

On to the next timepicker js widget but I thought I would let you know for the next person.

**Comment by mrhota** [comment]
Please download a release archive and use the js and css files found there. The bower link has been fixed.

Thanks
