### ISSUE TITLE
Remove 0 when hour is single digit

### ISSUE THREAD

**Issue by DevanB** [jdewit/bootstrap-timepicker#174]
I have successfully been using bootstrap-timepicker (yay!) for a while now and have noticed that when a user selects an hour that is a single digit, the timepicker appends a  0 to the front of it (ie 08:30). However this is not happening on the documentation page, and I can not find any documentation on how to change it, nor can I find it in the actual js file.

I would like to replicate this and only have a single digit (no 0 appended) if the hour is a single digit. Any way to do this? Thanks!

**Comment by pgelinas** [comment]
I do not have this behavior with timepicker. You can also check the Jasmine test cases (https://github.com/jdewit/bootstrap-timepicker/blob/gh-pages/spec/js/TimepickerSpec.js) which showcase a single digit hour not being prepended with 0. Are you sure you're using the latest version?

**Comment by DevanB** [comment]
Oh yes, I remember I was using another version of this to support Bootstrap 3. I updated and made my custom changes for BS3 now. Thanks!

**Comment by tsantos84** [comment]
There is some way to prepend the the digit with 0? I'm using timepicker with jquery validation. The "time" method expects "00:00" format to be a valid time. How can I work around this?
