### ISSUE TITLE
Picker displays NaN if input field has something other than a time

### ISSUE THREAD

**Issue by reedlaw** [jdewit/bootstrap-timepicker#18]
Not sure if this is a bug, but it would perhaps be more usable if something else was displayed other than "NaN". This could be a default time (current maybe) or a validation error. Or perhaps prevent characters other than those that match a regex (e.g. /\d{1,2}:\d{1,2}\s[AP]M/).

**Comment by aflx** [comment]
https://github.com/jdewit/bootstrap-timepicker/pull/21
