### ISSUE TITLE
Cannot run grunt test or grunt compile

### ISSUE THREAD

**Issue by newmanw** [jdewit/bootstrap-timepicker#185]
When I try and run grunt test or grunt compile I get:

grunt-cli: The grunt command line interface. (v0.1.10)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

If I install grunt locally in the project and try to run grunt test I get:

grunt test
Loading "jshint.js" tasks...ERROR

> > Error: Cannot find module 'jshint'
> > Warning: Task "jshint" not found. Use --force to continue.

Aborted due to warnings.

What am I doing wrong?

**Comment by mrhota** [comment]
did you run `npm install && bower install`?

I'm closing for now.
