### ISSUE TITLE
Problem to change from 23 hours to 00 when you click in arrow up. 

### ISSUE THREAD

**Issue by rubenns** [jdewit/bootstrap-timepicker#188]
When 23 is shown and you click in arrow up the value is not changed, the second time the value is changed to 01.

This problem is fixed if you update the the time (this.update()):

 incrementHour: function() {
      if (this.showMeridian) {
        if (this.hour === 11) {
          this.hour++;
          return this.toggleMeridian();
        } else if (this.hour === 12) {
          this.hour = 0;
        }
      }
      if (this.hour === 23) {
        this.hour = 0;
        this.update();
        return;
      }
      this.hour++;
      this.update();
    },

**Comment by mrhota** [comment]
I'm not sure how to repro this. Closing.

Please file another ticket if you're still experiencing this with version 0.3 or higher.
