### ISSUE TITLE
Clicking on hour/minute/second/meridian field under IE8 throws error

### ISSUE THREAD

**Issue by tempaowca** [jdewit/bootstrap-timepicker#189]
How to reproduce:
1. open any site with timepicker under IE8 browser (e.g. http://jdewit.github.io/bootstrap-timepicker/)
2. open timepicker widget
3. click on hour/minute/second/meridian field on the widget
4. on the console we get: 

```
Object doesn't support this property or method
```

The problem is in line 994 of bootstrap-timepicker.js file:

``` javascript
if ($input.is('input')) {
   $input.get(0).setSelectionRange(0,2);
}
```

IE8 does't support setSelectionRange method.

Solution is quite simple:

``` javascript
if ($input.is('input')) {
   var input = $input.get(0);
   if (input.setSelectionRange) {
     input.setSelectionRange(0,2);
   } else if (input.createTextRange){
     var range = input.createTextRange();
     range.collapse(true);
     range.moveEnd('character', 2);
     range.moveStart('character', 0);
     range.select();
   }
}
```

It solves the issue. setSelectionRange appears in file more times so it would be recommended to change those appearances as well.

**Comment by mrhota** [comment]
IE8 isn't supported by MS. I'm not going to bother with it either unless there's a compelling reason.

**Comment by tempaowca** [comment]
Thanks for answering almost 2 years after the issue was created. MS is still supporting IE8 - till January 2016. Solution is very simple but after 6 months it won't matter so don't bother...

**Comment by mrhota** [comment]
The snark is not appreciated. I just picked up maintainership; notice I'm not the author.

**Comment by tempaowca** [comment]
It was just a correction to your incorrect comment. I did not mean to offend you, sorry.
