### ISSUE TITLE
problem setting custom orientation

### ISSUE THREAD

**Issue by ogavrushev** [jdewit/bootstrap-timepicker#192]
Hi! There is a problem with setting orientation option, it says that object has no method addClass. So there is a typo at 626 line. Replace this.picker with this.$widget and I assume that the name of the class must be timepicker instead of datepicker. Thanks!

**Comment by mrhota** [comment]
I have merged this fix into #281. If you still care, your feedback would be appreciated.

**Comment by mrhota** [comment]
fixed by merging #281
