### ISSUE TITLE
Quick fix to use timepicker on bootstrap .modal

### ISSUE THREAD

**Issue by taivo** [jdewit/bootstrap-timepicker#197]
I was investigating why timepicker did not get displayed properly when used as a component of a custom bootstrap modal, I traced the problem to z-index always being NaN due to this line:

`var zIndex = parseInt(this.$element.parents().filter(function() {}).first().css('z-index'), 10) + 10;`

The empty filter function always returns an empty object. Can we replace this with something simpler like

```
var zIndex = parseInt(this.$element.css('z-index'), 10);
zIndex = isNaN(zIndex) ? 'auto' : zIndex+1;
```

This way, z-index can be customized by setting the original input element's z-index.

Alternatively, something more sophisticated that mimics jqueryUI's zIndex() would work as well

**Comment by mrhota** [comment]
Closing as dup of #204
