### ISSUE TITLE
Updating to Bootstrap 3 ?

### ISSUE THREAD

**Issue by bertrand-caron** [jdewit/bootstrap-timepicker#201]
Hi guys,

Great stuff you got going there. 

Are there any plans to move it towards Bootstrap 3 ? 
There are a lot of changes with v3 that break with your current version. I forked(https://github.com/bertrand-caron/bootstrap-timepicker) and fixed some but it is still far from being clean. 

Any help would be greatly appreciated ;)

Cheers, Bertrand

![capture decran 2014-01-20 a 20 23 01](https://f.cloud.github.com/assets/4724439/1957412/51d0ce72-8208-11e3-9a86-b086bad1cd41.png)

**Comment by zyberspace** [comment]
Hi,
looks like @neelprahalad  did all the work for you with #213 and #214.
You could merge both pull-requests in your repo, test it and then do a new complete pull-request with some description (so it's not more splitted up in two pull-request). :+1: 

As far as i saw, there are 3 pull-request (#213, #214, #215) for an update to Bootstrap 3 and 2 other issues (this and #205) that want an update to it.

**Comment by zyberspace** [comment]
https://github.com/nholling/bootstrap-3-timepicker looks also good.

**Comment by nholling** [comment]
My fork pointed to by zyberspace should be a drop in replacement for bootstrap-timepicker but for bootstrap 3.  All unit tests are passing currently as you would expect.  So things should be working as expected.

**Comment by dandv** [comment]
Hey @jdewit, still alive? :)

**Comment by fredngo** [comment]
Another +1 vote for Bootstrap 3 support

**Comment by mrhota** [comment]
This is complete in v0.5 (PR #275). See the Release tab on the main page and download a zip or tarball. :smile:
