### ISSUE TITLE
z-index not taking...

### ISSUE THREAD

**Issue by aabes** [jdewit/bootstrap-timepicker#204]
I'm popping up a timepicker in a modal, and crazy env with lots of z-indexes spattered around (and angular is involved too)
The html looks like this:

```
                    <div id="deliver_time" class="input-append bootstrap-timepicker" style="z-index:2000">
                        <input id="deliver_time_picker" type="text" class="add-on" ></input>
                        <span class="add-on" >
                            <i  class="icon-time"></i>
                        </span>
                    </div>
```

Note the explicit z-index, as an attempt to pop the picker to the top of the fray. Alas, it doesn't do the right thing.

A quick hack to remove the filter(function() {}) here: https://github.com/jdewit/bootstrap-timepicker/blob/gh-pages/js/bootstrap-timepicker.js#L617

seems to make things happier.

If I'm not missing something, I'd be happy to issue a pull...

**Comment by mrhota** [comment]
This should be fixed. There is a test which uses DOM structure similar to that written above.
