### ISSUE TITLE
timepicker with Bootstrap 3

### ISSUE THREAD

**Issue by ghost** [jdewit/bootstrap-timepicker#205]
Please share plan for timepicker with Bootstrap 3

**Comment by tanhevg** [comment]
I have made some tweaks to timepicker to make it work with Bootstrap3.1.1, at least in my use case. I am a bit new to the GitHub process, so if someone could guide me through the necessary steps (or point to a decent doc), I could commit a patch.

**Comment by mrhota** [comment]
closing as dup of #201
