### ISSUE TITLE
Miliseconds handling

### ISSUE THREAD

**Issue by bl4de** [jdewit/bootstrap-timepicker#206]
Hi,
Currently I use your bootstrap-timepicker plugin in one project, and we (me and my colleagues from devteam) had to implement handling for miliseconds.

Because we think not only we needed this feature, I'm wondering if you could take a look at our work and maybe you will be interested in merging this into bootstrap-timepicker component.

If yes, give me a couple of days to test our feature, write some tests (because at this moment tests don't pass) and I'll create PR from my feature branch. Currently I'm finishing implementation of 'Tab' switching between form fields if 'showMiliseconds' option is on (it's working quite well so far). 

Looking forward for your answer :)

Greetings,

bl4de

**Comment by mrhota** [comment]
Hi, I'm maintaining the plugin now. Please check out one of the new releases. I haven't implemented millisecond handling, although I created an issue for it #277.

Let me know if the newer versions fix the tabbing issue, too. I'd be happy to take a look at whatever millisecond handling you currently have.

Thanks,

**Comment by bl4de** [comment]
Hi,

Thanks for answering. Unfortunately I can't check if your changes fix problems because I'm not working in that company anymore :)

You can take a look at miliseconds changes here:
https://github.com/bl4de/bootstrap-timepicker/commit/dc878a4e17a7ed251ac1d5aea14d5fe90e6a1227

but it might be not a good experience as I've used different code formatting and all lines look to be changed.
