### ISSUE TITLE
24hr format issue

### ISSUE THREAD

**Issue by comtom** [jdewit/bootstrap-timepicker#208]
When meridian is disabled, hours should be between 00 and 23. Instead, if hours are less than ten, a one digit number shows up (0 to 9, instead of '00' to '09'.

It would be awesome to fix this as it is nicer, more consistent (minutes values work like expected) and relational databases expect a 'XX:XX' format, so I think is the best option.

Thanks for your work

**Comment by mrhota** [comment]
I prefer the config to be called `twoDigitHour`. Will fix during merge.
