### ISSUE TITLE
autotype dependency

### ISSUE THREAD

**Issue by jfroffice** [jdewit/bootstrap-timepicker#233]
I do not see any benefits about adding `autotype` dependency excepting for test executions.

Maybe the `autotype` dependency should be only for `DevDependencies`, on `bower.json` file.

**Comment by darky** [comment]
:+1:

**Comment by orangejuicy** [comment]
+1

**Comment by ldonnet** [comment]
+1 because mmonteleone/jquery.autotype has no versions defined

**Comment by ldonnet** [comment]
Is it possible to merge @orangejuicy commit or fix version for autotype? I would like to use your awesome work with rails-assets but I can't because mmonteleone/jquery.autotype has no versions defined.

**Comment by mrhota** [comment]
Making these changes in bs3upgrade branch
