### ISSUE TITLE
add one hour to the output in $this.val() in timepicker

### ISSUE THREAD

**Issue by oozmac** [jdewit/bootstrap-timepicker#244]
how do you add an hour to the result of   

```
$('#breaktime').timepicker({
      'step': 60,    
      'minTime': '7:00am',    
     'maxTime': '10:00pm', });   

$('#breaktime').on('changeTime', function() {     
$('#onselectTarget2').text($(this).val()); });
```

if i selected 12:00pm, the output should be 1:00pm

I need to have the result with additional hour. I have been trying for hours and I don't have a clue.

**Comment by mrhota** [comment]
can you call `getTime()` on the timepicker, and add an hour to it using Moment? Or you can do the arithmetic yourself on the timepicker fields: `$("#timepicker-el").data('timepicker').hour + 1`

**Comment by mrhota** [comment]
We can re-open if the above doesn't help. Let me know. Thank you!
