### ISSUE TITLE
Can we set the min and max time ?

### ISSUE THREAD

**Issue by pravin-d** [jdewit/bootstrap-timepicker#246]
Is there a way to set the min and max time a user can select using the timepicker library ?

**Comment by Saranya-Raaj** [comment]
:+1:  for this request.

**Comment by vigneshgurusamy** [comment]
+1

**Comment by christopher-mazaudou** [comment]
I agree

**Comment by lyziane** [comment]
+1

**Comment by jonasklering** [comment]
+1

**Comment by mmarchini** [comment]
We implemented the option to set a max hour for the field:

https://github.com/jdewit/bootstrap-timepicker/pull/261

**Comment by mrhota** [comment]
Already merged. See `maxTime` option.

**Comment by magnosis** [comment]
I'm using version 0.5.2.

There is no maxTime option.
There is no minTime option either.

There is only maxHour.

So there is no control on the max Minute, or min Time at all?

**Comment by AbdallahBedir** [comment]
If there is `minHours` would be great.
