### ISSUE TITLE
Adding text inputs to fill hours, minutes and seconds

### ISSUE THREAD

**Issue by hhamon** [jdewit/bootstrap-timepicker#25]
Hi,

First of all, thank you very much for this great piece of JS library. It saved lots of my time!

I would like to know if it would be possible to have an option to display hours, minutes and seconds in input fields or edit in-place placeholders instead of plain text so that we can manually change them without scrolling with the top and bottom chevrons.

Do you think it would be a nice enhancement?

**Comment by jdewit** [comment]
Hi Hugo,

Great idea. I just finished implementing it. Let me know what you think!

**Comment by hhamon** [comment]
You're awesome! I will try it today or tomorrow and will let you informed :)

Many thanks!

**Comment by hhamon** [comment]
I've just tried it and it works like a charm. Thanks :)
