### ISSUE TITLE
'.js' file and '.min.js' file are different?

### ISSUE THREAD

**Issue by songgun** [jdewit/bootstrap-timepicker#253]
Hi, It's my first github post, and my English is not good. Hope you understand.

'getTime' function code of 'bootstrap-timepicker.js' file is start with...

......
getTime: function() {
    if (this.hour === '') {
        return '';
    }
    ......

but, 'getTime' function code of 'bootstrap-timepicker.min.js' file is start with...

```
...... getTime:function(){return this.hour||this.minute||this.second?(this ......
```

It's OK?
These two files behave differently.
Is it intentional code?

**Comment by mix3d** [comment]
according to this commit: https://github.com/jdewit/bootstrap-timepicker/commit/cefe33ee70ae2c6a995ab232016f9059d9dc606c

this is intentional. If you look at the last updated timestamps for both files, you'll see that the .min.js version hasn't been updated in a while.

**Comment by mrhota** [comment]
they should be the same now.
