### ISSUE TITLE
Give someone else commit/merge access.

### ISSUE THREAD

**Issue by mrhota** [jdewit/bootstrap-timepicker#264]
People still use this plugin, and some apparently still believe you're maintaining it. The alternatives and forks are problematic in their own ways. It'd be nice to see some merging, bug-fixing, and new releases. If no one else steps forward, I'd be willing to give it a shot.

**Comment by jdewit** [comment]
I made an issue awhile back looking for help. I don't use this plugin any more so it's hard to find the time to maintain it. 

Anyone who wants commit access just ask.

**Comment by mmarchini** [comment]
@jdewit I'm willing to help maintaining this plugin.

**Comment by mrhota** [comment]
Dang, I just noticed that. Sorry, @jdewit. Thanks for the rapid response. I'll start grooming the issues tonight.
