### ISSUE TITLE
Use mouse scroll to change values

### ISSUE THREAD

**Issue by mmarchini** [jdewit/bootstrap-timepicker#273]
It would be nice if we could scroll values up and down using the mouse scroll.

**Comment by mrhota** [comment]
I'm torn about this. Scroll wheel scrolls through `<select>` options, but bootstrap-timepicker isn't a `<select>`. On the other hand, the timepicker is _sort of_ like a `<select>`...

What I don't want to do is blow someone's mind with unexpected behavior for something as important as a scroll action. Could the scroll-to-change-values action be isolated to the widget?

**Comment by mmarchini** [comment]
Yeah, it would be isolated to the widget. It could also be something optional, being disabled by default.

I'll try to code this and create a Pull Request to express the idea better.
