### ISSUE TITLE
"datepicker-orient-" class?

### ISSUE THREAD

**Issue by jackvial** [jdewit/bootstrap-timepicker#276]
Why does the timepicker default to using the "datepicker-orient-auto" class? I don't see it defined anywhere in the timepicker css or bootstrap core css.

![image](https://cloud.githubusercontent.com/assets/5176927/9086487/bafc69e2-3b52-11e5-9215-a6ccbd3a1655.png)

**Comment by mrhota** [comment]
That's a good question. Could it be simply a hook for your own styles, if needed?

**Comment by mrhota** [comment]
Oh wait. The class is `datepicker`, not `timepicker`. See #192, #181, and PR #229.

**Comment by mrhota** [comment]
@jackvial I have merged a probable fix for the above-mentioned issues into #281. If it's convenient, can you check out that PR?

**Comment by mrhota** [comment]
fixed by PR #281.
