### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by MartijnR** [jdewit/bootstrap-timepicker#287]
I think it just requires the following addition to package.json:

```
"main" : "js/bootstrap-timepicker"

```

**Comment by mrhota** [comment]
Thanks for the report. I know nothing about configuring packages for npm support. Could you issue a PR? Or do you have some sources for fixing it?

**Comment by MartijnR** [comment]
will send PR

It's actually not really broken, but currently you'd have to do 

```
require('bootstrap-timepicker/js/bootstrap-timepicker')
```

 instead of the more convenient

```
require('bootstrap-timepicker')
```

reference: https://docs.npmjs.com/files/package.json
