### ISSUE TITLE
Feature request: Empty field are empty, not 01:00

### ISSUE THREAD

**Issue by betacar** [jdewit/bootstrap-timepicker#29]
If a timepicker field has no value, with `defaultTime: 'value'`, it shows a default hour (01:00). It would be great if the field stay empty. However, when the timepicker is shown, the hour in the picker would be the current time (or some value set by a data attribute).

This request is very similar to the `'setStartDate'` method that [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker#setstartdate) uses.

**Comment by reustle** [comment]
I'm not sure if this is related to this request, but I'd like to see it be able to stay empty as well. I also don't like how it fills in a time automatically on init.

**Comment by th3n3rd** [comment]
try to use defaultTime: false, it should work!

**Comment by jdewit** [comment]
Yes. defaultTime: false is the way to do it. 'value' has been deprecated. 

Thanks!
