### ISSUE TITLE
Open widget when clicking the input

### ISSUE THREAD

**Issue by Dimas-sc** [jdewit/bootstrap-timepicker#298]
Hi,
Is it possible to open the widget when clicking the input field? At the moment the widget is opened only when clicking the icon.
Thx

**Comment by mrhota** [comment]
No, sorry. That's by design.

You could probably attach an event handler to the input so that the timepicker widget appears.

**Comment by mrhota** [comment]
Any luck? Can I close this?

BTW, to be explicit: you'll want to attach a click handler to the input and execute the method `$('#timepicker').timepicker('showWidget');`

**Comment by Dimas-sc** [comment]
Yes, it worked, thx!
