### ISSUE TITLE
Internet explorer 8 (IE8) and glyphicons 

### ISSUE THREAD

**Issue by zagros** [jdewit/bootstrap-timepicker#299]
Hello,

I have an issue with IE8 and glyphs in this widget.  They do not show in IE8 until I hover on top of the up/down arrows. 

The rest of the glyphs (there are many) on my page show normally (PS: like many I have support for glyphs in IE8 courtesy of html5shivs.js and respond.js scripts).

As a note, I looked at your own website in IE8 (http://jdewit.github.io/bootstrap-timepicker/) and I see squares much the same. 

Also to hotfix for the time being, we changed the plugin's source to call $(eachOfThoseButtons).focus() when the time panel pops up.

![untitled](https://cloud.githubusercontent.com/assets/157666/10466350/e8562644-71c1-11e5-8880-67b1c6347e6e.png)

**Comment by mrhota** [comment]
I'm really sorry; we're using jQuery 2.0. They dropped support for IE8 in 1.9. Microsoft is ending general support for IE8 in January, which is only a few months away, so it's not really worth special-casing the code and tests just for IE8.

Is there _any_ possibility that you can drop support for IE8 in your application? No one _wants_ to develop for IE8 (right???).

I'm sorry this isn't much help. :-/

**Comment by zagros** [comment]
fair enough, we keep the focus fix for now.  let's hope we can get rid of ie8 real soon (although that's not possible now)!

**Comment by mrhota** [comment]
I haven't tested this, but can you use bootstrap-timepicker with jquery 1.9 or lower? Seems like you should be using a version less than 1.9 anyway, since you're trying to support ie8.

If you're not already using less than jquery 1.9, what happens to the buttons when you do?

**Comment by mrhota** [comment]
Feel free to leave a comment, for posterity's sake. I'm closing this for now.
