### ISSUE TITLE
Tabbing through input does not work

### ISSUE THREAD

**Issue by brandonb927** [jdewit/bootstrap-timepicker#30]
I'm not sure if this has been brought up, but when tabbing through several inputs, then reaching an input marked up with `class="timepicker-default"`, the curser becomes stuck and the only way to recover from this is to refresh the page. Even after picking a time, the cursor is still stuck.

Scenario: [jsfiddle](http://jsfiddle.net/4c3HW/1/)

**Comment by robertwritescode** [comment]
I am experiencing the same issue. This also occurs if you click into an input controlled by a timepicker with the control appended to the right.

**Comment by brandonb927** [comment]
I haven't looked through any of the source, is there a way to mitigate this easily?

**Comment by jdewit** [comment]
this has been fixed. Thanks!
