### ISSUE TITLE
Blur doesn't hide the timepicker

### ISSUE THREAD

**Issue by tobiascapin** [jdewit/bootstrap-timepicker#304]
I'm filling a long form with timepickers in Firefox v.41.

If I use mouse to focus on fields everything works, if I use tab key to move the focus from one field to other, once focus on a timepicker its widget doesn't hide itself on blur. To hide it I need to click somewhere else.

**Comment by justinnichols** [comment]
I believe I have a fix ready for this.  I'm working to get a pull request in.

**Comment by justinnichols** [comment]
Pull request https://github.com/jdewit/bootstrap-timepicker/pull/306 has been submitted for this.

**Comment by justinnichols** [comment]
Pull request https://github.com/jdewit/bootstrap-timepicker/pull/307 has been submitted for this.

**Comment by mrhota** [comment]
#307 was merged. Tabbing out of timepicker el should close the widget.
