### ISSUE TITLE
Can not type if template is not presented within Chrome

### ISSUE THREAD

**Issue by Goodgulf** [jdewit/bootstrap-timepicker#31]
I've tested this on both Linux and Mac Chrome.  It works fine if the template is enabled, but does will not allow typing into the input when {template: false} is passed in.

Same behavior is reflected on the demo/documentation site.

**Comment by sepehr** [comment]
I second this. In my case the input does not work even if the template is set. (Chrome 21.x)

**Comment by ejain** [comment]
Ran into this problem as well: Can't edit values with {template: false} in Chrome 21.x. Works with Firefox 15.x.

**Comment by alindsay55661** [comment]
This is also a problem for me with Chrome 22 on Mac. It will not allow typing even if template is specified.

**Comment by henne001** [comment]
Indeed... same here. No manual input possible in Chrome 22.0.1229.94, with or without specifying templates.

I do notice that it does allow some inputs. The '.' on numeric pad works, and with '&', ''', '(' you can increase and decrease the values.

Did this work in previous versions of Chrome? Haven't tested yet.

**Comment by 010Minds** [comment]
Hi!

In elementKeypress function, the e.KeyCode return 0 in FF and in Chrome return the correct keyCode. I don't know why this, but i comment the line (near 297) after if if (e.keyCode !== 0 && e.keyCode !== 8 && e.keyCode !== 9 && e.keyCode !== 46) and works fine to me. I know that isnt the best way.

If someone can verify more, maybe it can help.

Regards
