### ISSUE TITLE
No longer published on npm

### ISSUE THREAD

**Issue by MartijnR** [jdewit/bootstrap-timepicker#310]
https://www.npmjs.com/search?q=bootstrap-timepicker

Is that by accident?

**Comment by mandric** [comment]
Same here... was it folded into bootstrap-datepicker or something?  Still doesn't make sense to unpublish it for projects that might still be using older versions.

**Comment by mrhota** [comment]
It was "unofficial". I'll publish tonight.

**Comment by mrhota** [comment]
ok, i'm publishing v0.2.7 (sorry), v0.3.0, v0.5.0, and v0.5.1.

I also updated the github releases tab so the above tags have release tarballs and zips.

**Comment by alxndrsn** [comment]
Thanks!

**Comment by mrhota** [comment]
Closing for now. Reopen if there are lingering issues.

**Comment by MartijnR** [comment]
Thanks!
