### ISSUE TITLE
IE8 click on popup's input

### ISSUE THREAD

**Issue by ngocnv371** [jdewit/bootstrap-timepicker#333]
Using IE8, show the popup to choose the time, then click on the input for 'hour'. An error appeared complaining that the function setSelectionRange is not supported.

**Comment by mrhota** [comment]
Sorry, we're using jQuery 2.x. http://blog.jquery.com/2013/04/18/jquery-2-0-released/

No more IE8. :frowning:

You might have some luck with an older version of this plugin: see the releases tab and look in `bower.json` for `jquery: 1.x` or similar.

Closing for now.
