### ISSUE TITLE
Is there a date-picker to change date using arrow keys like yours

### ISSUE THREAD

**Issue by sanals** [jdewit/bootstrap-timepicker#334]
Is there a Bootstrap datepicker, where I can change day, month, and year with the arrow keys alone like this timepicker here. This timepicker seems faster than all the datepickers available.Or is it possible to configure bootstrap datepickers to work that way. I know datepicker dates can be changed with ctrl and shift keys.

**Comment by mrhota** [comment]
Sorry, not that I know.
