### ISSUE TITLE
Position with bootstrap

### ISSUE THREAD

**Issue by MittchoBaroco** [jdewit/bootstrap-timepicker#340]
Hi have some issues with my position can you help me ?
![screen shot 2016-05-10 at 11 33 53 am](https://cloud.githubusercontent.com/assets/14871530/15141999/43a8ceda-16a3-11e6-8b92-7269fa84dee3.png)

**Comment by pmartynov** [comment]
Hi, @MittchoBaroco !
Hopefully this PR https://github.com/jdewit/bootstrap-timepicker/pull/342 will fix your problem.

**Comment by MittchoBaroco** [comment]
yep it's working now thank you very much :+1:
