### ISSUE TITLE
Any plans for bootstrap 4 support?

### ISSUE THREAD

**Issue by EugenMayer** [jdewit/bootstrap-timepicker#347]
We have been using bootstrap timepicker with bootstrap 2 with good success and are currently using bootstrap 4 pretty heavily and would love to see bootstrap-timepicker to be part of the familiy

Do you have any particular plans for bootstrap 4? Were do you expect things to change, mainly CSS wise?

**Comment by mrhota** [comment]
I know nothing about bootstrap 4, so your best bet is a PR with the correct changes.

**Comment by alensiljak** [comment]
+1
New projects are starting with bootstrap 4 by default so I guess we need to find a new time picker or look into upgrading this one.

Fortunately, at the moment it seems fairly simple. The only change I see is that the glyphicons need to be replaced by something else, i.e. font-awesome.
