### ISSUE TITLE
Passing option via data-fields

### ISSUE THREAD

**Issue by silviorelli** [jdewit/bootstrap-timepicker#39]
It's not documented, but looking at your code I found that we can pass the options to the timepicker via data-fiels.

For example I'm setting the time using a 'data-default-time'.

Can you update the documentation? I could not issue a pull request as the documentation is on your own site instead of github :)

**Comment by harobed** [comment]
+1

**Comment by ssharunas** [comment]
Actually documentation in README.md links to http://jdewit.github.com/bootstrap-timepicker/ , therefore you can update documentation (checkout gh-pages branch an send pull request) if you really want to :)

**Comment by jdewit** [comment]
contributing is the right thing to do!

**Comment by philsturgeon** [comment]
I'd also be interested in seeing how the data attributes work. Please do contribute the correct answers to the documentation.

**Comment by jdewit** [comment]
fixed in e204c836e3a62c7ad872260222a1277a8cc4db7b

check docs for use.
