### ISSUE TITLE
How do I open the timepicker from another element?

### ISSUE THREAD

**Issue by Hani79** [jdewit/bootstrap-timepicker#45]
How do I reference the timepicker (and the hideWidget method) from another script?  I basically have a button that I want to use to open the timepicker.  I assume it would be something similar to the link in the code that says:

this.$element.parent('.input-append').find('.add-on').on('click', $.proxy(this.showWidget, this));

However, how do I reference the TimePicker itself since it isn't "this" in another script?

**Comment by jdewit** [comment]
$('#timepicker').timepicker('showWidget);

**Comment by sanketkumar** [comment]
@jdewit How do I close one timepicker on click of another? I have implemented 2 of them, for start and end time. Currently both remain open at once.
Thanks

**Comment by mrhota** [comment]
Do you have code that you've tried? You could try adding a click handler for the first one which closes itself and opens the other.

You call timepicker methods with code like `$(selector).timepicker('methodName')`

I think the method you want is `hideWidget`. Let us know if that's helpful.

**Comment by sanketkumar** [comment]
Nope this did not work for me. And it was the first thing that I had tried.
Anyways adding separate parent containers for both the input fields did the trick for me. Still havent figured out the reason for that though.

**Comment by mrhota** [comment]
Please add the relevant HTML and javascript so we can help.

**Comment by mrhota** [comment]
question has been answered
