### ISSUE TITLE
Timepicker doesn't disappear when you get out of input using 'tab'.

### ISSUE THREAD

**Issue by hugomn** [jdewit/bootstrap-timepicker#46]
When you navigate trough timepicker input using tab key, the picker shows correctly but when you go to the next field it doesn't disappear.

**Comment by wilerson** [comment]
Just ran into this as well, made a quick fix for that. I have also noticed that, if you click into a select field, the dropdown wouldn't hide either.

**Comment by jdewit** [comment]
I can't reproduce this error anymore. Let me know if you can.

**Comment by silviomoreto** [comment]
It keeps not working.
If you have 2 timepicker in a page and press tab to swap between them, the dropdown doesnt dissapear

I guess is because the mask on the input is not working to

**Comment by wuliupo** [comment]
Yes, I can reproduce.
- After insert date and time, if you click the richedit content, the timepicker widget does disappear. It is another iframe. Maybe we can add a mask on the whole page.
- Using keyboard 'TAB' event to focus timepicker, and 'TAB' to other contollers, the widget does disappear too.

**Comment by gschuager** [comment]
+1

**Comment by aarondfrancis** [comment]
+1

**Comment by disider** [comment]
+1
