### ISSUE TITLE
Bug: Blank Input + defaultTime: 'value' = 00:00:00

### ISSUE THREAD

**Issue by Jakobud** [jdewit/bootstrap-timepicker#51]
If I apply `.timepicker()` to an empty text input and I'm using 'defaultTime' : 'value' the time comes up as `00:00:00`.  It should be left blank.  In the case that you are pulling the time from a database and the database value is NULL or "", you would want the input to remain blank, not be automatically filled in with 00:00:00....

**Comment by jdewit** [comment]
the value option has be deprecated. Just set the value directly with javascript or html.
