### ISSUE TITLE
Manual input in IE9 doesn't work

### ISSUE THREAD

**Issue by martijnlaan** [jdewit/bootstrap-timepicker#57]
Maybe related to #31 : If you go to the demo page at http://jdewit.github.com/bootstrap-timepicker/ using IE9 and click the first input and press a key like '1' nothing happens. Using the debugger I saw that elementKeypress' e.keyCode equals 49 but it's expecting 0 (under Firefox it indeed is 0 if '1' is pressed).

Additionally under IE9: pressing the up or down arrow key doesn't do anything because elementKeypress isn't being called.

Also the demo page hangs (100% CPU) under IE9 if you click on the second input because it keeps switching focus between the first and second input.

**Comment by SepiaGroup** [comment]
the demos do not work in IE9.  to solve this replace keypress with keyup in the init.  (lines 62 and 77)

sorry just don't have time right now to do a pull request.

**Comment by jdewit** [comment]
Thanks. This should be fixed now with a77666e24dd8e86f0f42a175b162e11df2f16e0e
