### ISSUE TITLE
Object [object Object] has no method 'timepicker' 

### ISSUE THREAD

**Issue by Dieterbe** [jdewit/bootstrap-timepicker#61]
my code:

```
<div class="input-append bootstrap-timepicker-component">
    <input type="text" class="timepicker-default input-small">
    <span class="add-on">
        <i class="icon-time"></i>
    </span>
</div>
        <script type="text/javascript">
        $(document).ready(function() {
            $('.timepicker-default').timepicker();
      });
      </script>
```

i tried with and without the surrounding document ready callback.
using the latest bootstrap-timepicker.js from git, jquery 1.7.2, bootstrap.js 2.0.4 , jQuery UI 1.8.15 (though disabling jquery-ui doesn't fix it)

**Comment by jeffcombs** [comment]
n/m, all my stupid mistakes.  First error referenced was because js file wasn't loading properly.

**Comment by Dieterbe** [comment]
why is this closed? i'm still seeing the issue, and i'm including the js files properly (as described in the OP).
also, what does 'ple' mean?

**Comment by jdewit** [comment]
Sorry, thought it was you that said you fixed it. 

I can't reproduce this issue. Make a fiddle and I'll have a look.
