### ISSUE TITLE
Timepicker not repositioning near edge of screen

### ISSUE THREAD

**Issue by raduluchian** [jdewit/bootstrap-timepicker#65]
The thing keeping me and my team from using this neat component is the fact that the timepicker doesn't reposition itself when the input is near the edger of the screen. This causes horizontal scrolling to appear, interferes with design elements and downgrades the UX grately. This is something that doesn't occur in <a href="http://jqueryui.com/datepicker/">jQuery UI's Datepicker</a>. See the screenshots bellow for better understanding of the issue:
![bootstrap-timepicker-bug](https://f.cloud.github.com/assets/1701520/64557/d1d0d87a-5e4f-11e2-887e-954a5cc9d603.jpg)

**Comment by jdewit** [comment]
Thanks for the heads up. This has been fixed. Check out the demos.
