### ISSUE TITLE
timpicker within a bootstrap modal window

### ISSUE THREAD

**Issue by jeffcombs** [jdewit/bootstrap-timepicker#68]
I recently updated to bootstrap 2.2.2 and using a form within a modal.  Timepicker is no longer showing up, but datepicker does work.  Not sure if this is just a z-index issue.

**Comment by jdewit** [comment]
I'm using 2.2.2 as well on the docs and it works http://jdewit.github.com/bootstrap-timepicker.

Have you updated to the latest timepicker? A lot has changed in the last few days.

**Comment by jeffcombs** [comment]
Yea, sorry, I just noticed a div wrapper with class bootstrap-timepicker.  I added that and it works, just have to mess with the styling to make this inline with the datepicker input.

**Comment by nataliarosa9** [comment]
Hi, i have a problem for use the timepicker inside modal windows. When I'm click shows two popups! Can you help me ? 
See the photo!!
![timepicker](https://f.cloud.github.com/assets/6066985/1744106/3f915a60-6417-11e3-86a3-8548325863f1.png)

I wrote this code for do the timepicker work, but now I created this problem! 

$('.bootstrap-timepicker input').timepicker({
    showMeridian : false
}).on(
    'changeTime.timepicker',
    function(e) {
        var dataSelecionada = moment().format(
                'DD/MM/YYYY ' + e.time.value + ':00');
        $(this).parent().find('.date-value').val(dataSelecionada);
        });

Help me please!!!

**Comment by jdewit** [comment]
Can you show me an example in a jsfiddle?

**Comment by nataliarosa9** [comment]
This is my example : http://jsfiddle.net/nataliarosa9/gp92U/9/

Thank you!!

**Comment by OsamaKhodroj** [comment]
Hi,

I have the save issues and it's dos't solve can any help me ????

Osama Khodrog
Founder at : http://arabisky.com/country
you can visit our website for Jordan : http://jo.arabisky.com/

**Comment by mrhota** [comment]
If you need help, we need details. What version are you using? What does your code look like?

Thanks!
