### ISSUE TITLE
inputs don't come up if retrieved via ajax

### ISSUE THREAD

**Issue by patrickgordon** [jdewit/bootstrap-timepicker#69]
I am retrieving a php page using AJAX which has multiple input elements on it including time date and user entry fields.

The time picker field will initiate the correct time but no input fields will open up when focusing on the input.

Timepicker is initialised when the page is returned via AJAX.

can give an example if you need more to go off...

**Comment by jdewit** [comment]
Can you reproduce the error in a jsfiddle?

**Comment by lanks** [comment]
I am having the same issue with this plugin... It would be nice to be able to use it with forms that are loaded using ajax. Has anyone made any progress with this issue?

**Comment by jdewit** [comment]
You're calling the timepicker on the new instance after loading it right?

**Comment by jdewit** [comment]
Did you get it to work?

**Comment by lanks** [comment]
Hi

No sorry I did not get it to work...

Cheers
Liam

**Comment by jdewit** [comment]
Are you using livequery or calling .timepicker() on the loaded content?

**Comment by jdewit** [comment]
@lanks  please reply

**Comment by slbug** [comment]
Same thing. CoffeeScript code

``` coffeescript
$(document).on 'click', '.calendar-object a', (e) ->
  $.get $(this).attr('href'), (data) ->
    $('.sidebar').html(data)
    $('.timepicker').timepicker()

  e.preventDefault()
```

**Comment by slbug** [comment]
Nvm, looks like wrapping input in .bootstrap-timepicker required
