### ISSUE TITLE
Un-existent update.timepicker event

### ISSUE THREAD

**Issue by tomasAlabes** [jdewit/bootstrap-timepicker#70]
From documentation, we can subscribe to this event:

```
$('#timepicker').timepicker().on('update.timepicker', function(e) {
    console.log('The time is ' + e.time);
});
```

But the only events triggered in source code are 'show.timepicker' and 'hide.timepicker'.

Great work :+1:

**Comment by jdewit** [comment]
I got a little ahead of myself with the docs. The event is actually 'changeTime' now.
