### ISSUE TITLE
Modal not center on small screens

### ISSUE THREAD

**Issue by chrisfleisch** [jdewit/bootstrap-timepicker#72]
When using timepicker on a smaller screen the modal is not centered and half off the screen.

I've attached a image from the demo page:
![Screen Shot 2013-01-31 at 10 17 46 PM](https://f.cloud.github.com/assets/847769/117080/371a0e8c-6c1e-11e2-898e-c750508d6ad5.png)

**Comment by jdewit** [comment]
Thanks!
working on it at the moment.

**Comment by jakul** [comment]
You've commited these changes to the minified CSS file, but not to the normal one. Can you update the non-minified too?
