### ISSUE TITLE
 $element.get(0).setSelectionRange not supported in ie (testing in ie7)

### ISSUE THREAD

**Issue by jdaily** [jdewit/bootstrap-timepicker#75]
I'm getting a "Microsoft JScript runtime error: Object doesn't support this property or method" for this section of the code:

```
 setTimeout(function() {
        $element.get(0).setSelectionRange(0,2);
      }, 0);
    },
```

I'm still researching a possible fix, but any pointers would be great.

Thanks

**Comment by jakul** [comment]
I'm also seeing this issue & would appreciate a fix!

**Comment by jakul** [comment]
`setSelectionRange` [is only supported in IE9+](https://developer.mozilla.org/en-US/docs/DOM/Input.setSelectionRange). If you have a HTML5 shim that supports it then it'll probably work fine in IE7 etc, depending on the shim. I haven't been able to find any suitable shims that work.

`boostrap-timepicker` should either make these calls optional, or document that the library only works with IE9+

**Comment by jakul** [comment]
@jdewit Thanks for the quick response!

**Comment by fijolekProjects** [comment]
There's still problem clicking on hour/minute field, you will get "Object doesn't support this property or method" on IE8. I've added one setSelectionRange 'if' in "widgetClick" method like this:

<pre><code>if ($input.is('input')) {
  if ($input.setSelectionRange) {
    $input.get(0).setSelectionRange(0,2);
  }
}
</code></pre>

The error is gone, but it does not highlight input and its very unintuitive for the user. Is there solution to make it work on IE8?
