### ISSUE TITLE
bootstrap-timepicker.css doesn't contain ".bootstrap-timepicker-widget.dropdown-menu.open"

### ISSUE THREAD

**Issue by PhantomRay** [jdewit/bootstrap-timepicker#78]
Couldn't get the dropdown menu open. Figured out that bootstrap-timepicker.css doesn't have the definition of .bootstrap-timepicker-widget.dropdown-menu.open.

But the bootstrap-timepicker.min.css does have it. Please fix.

**Comment by leo-naeka** [comment]
+1

**Comment by marsuboss** [comment]
+1
