### ISSUE TITLE
Calling datepicker() breaks bootstrap's border radius on last child of input-append

### ISSUE THREAD

**Issue by samselikoff** [jdewit/bootstrap-timepicker#91]
The `bootstrap-timepicker-widget` is appended after the `span.add-on`, breaking the css border-radius rule for the last child of an `input.input-append`.

**Comment by jiehanzheng** [comment]
I can confirm this.  This issue can also be reproduced on the http://jdewit.github.io/bootstrap-timepicker/ page.

**Comment by mrhota** [comment]
not sure this is an issue with bootstrap 3
