### ISSUE TITLE
Approximate custom time values to "minuteStep's" and "secondStep's"

### ISSUE THREAD

**Issue by ghost** [jdewit/bootstrap-timepicker#97]
If "minuteStep" option (for example) is defined and equals 15 and user inputs "15:48", time value should update to "15:45" or "16:00" according to round method that should be defined too.

**Comment by mrhota** [comment]
calling this option `snapToStep`. The rounding near 59/60 rolls to 00, though. See #275

**Comment by mrhota** [comment]
fixed in 472f2f9
